### ISSUE TITLE
EUF and other corruption on WF Import

### ISSUE THREAD

**Issue by DerekMangrum** [ShepherdDev/rock-misc#2]
So, I tried this new code on my test system… And it does successfully import and export. There do seem to be some things, however, that aren’t quite right.

I did an export-delete-import on the ‘Profile Change Request’ workflow. After poking through the imported version, I saw…
![img001](https://user-images.githubusercontent.com/1100235/27354362-2b100740-55bc-11e7-9f38-3a81d4be5160.png)
![img002](https://user-images.githubusercontent.com/1100235/27354368-30b6f6cc-55bc-11e7-8a57-6ae54938123d.png)
Also, the ‘Capture Notes’ Action only has one button (also labeled ‘242’). This, of course, won’t work with the Action Run If filters on subsequent Actions.

**Comment by cabal95** [comment]
The `Set Name` step is a semi-known issue.  Attribute values that reference other Attributes are a bit tricky to track because it just stores a GUID value - but as far as we know it's just some random text. It's on my list to check if an AttributeValue's `Value` can be parsed as a GUID and if it can check if we have any known entities that match that GUID, and if so change the value to match the new GUID generated.

Not sure whats going on with the Command Label and how it became `242`.  What was the text before the export on that?

**Comment by DerekMangrum** [comment]
Not sure of the text/label on the button originally (I can try to hunt that down), but it would have been something like "Submit", "Update", "Cancel" or something like that.

**Comment by cabal95** [comment]
Okay good enough. I'll do some checking.  That is another one of those special cases I have code for. Something about it must have not detected. I think 242 is probably the DefinedValue Id number for that button.

**Comment by cabal95** [comment]
Here is an updated version of the WF export. I had to modify the json to work with the new format. I'm not 100% sure I got the button labels correct (other than the ROCK/PAPER/SCISSORS).

Also, there seems to be some logic glitches, unless you are running a customized version of Rock that makes it work.

1) In the workflow actions, there is no "did computer win" attribute and when it increments the score counts it always checks "Is Tie" attribute == False for both Computer and Player win testing.

2) In the lava that displays the round status, it always displays "you lost" because it compares the workflow attribute values to `false` instead of `"False"` (the boolean text "false" in the attribute value will not equate to a boolean false in lava).

It's possible these are due to some last minute tweaking that was done to the workflow before export or after it was last used.  Easy to fix but I didn't go that far.

[RockPaperScissors2.zip](https://github.com/ShepherdDev/rock-misc/files/1171511/RockPaperScissors2.zip)

**Comment by cabal95** [comment]
BTW, I wasn't able to replicate the `Workflow Set Name` action ending up with the Guid value in the text rather than a selected attribute. It's possible I have already fixed that and don't remember. If you happen upon it again and can replicate it let me know and I'll take a look.
